// <auto-generated />
namespace StreetFighter.RepositorioEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class criandotables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criandotables));
        
        string IMigrationMetadata.Id
        {
            get { return "201611090917293_criando tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
